project:
  type: website
  output-dir: docs

website:
  title: "Mapd'O"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: ebf.qmd
        text: Espace de bon fonctionnement
      - href: inondation.qmd
        text: Risque d'inondation
      - href: about.qmd
        text: A propos

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual
