---
title: "Espace de bon fonctionnement"
---

Dans le cadre d'une délimitation de l'espace de bon fonctionnement plusieurs métriques peuvent être mobilisées pour la description des tronçons du réseau hydrographique selon leur géomorphologie afin de construire des unités fonctionnelles. :

-   Le profil d'élévation du talweg permet l'analyse de la structure des pentes et des points de contrôle naturels et anthropiques.
-   Le fond de carte de la géologie pour identifier les secteurs sous contraintes géologiques et les zones de dépôt alluvionnaire.
-   Dans la recherche de tronçons représentatifs et de l\'évolution morphologique des cours d\'eau du bassin versant, de nombreuses ressources cartographiques et d\'imageries sont mises à disposition sur le site [remonterletemps.fr](https://remonterletemps.ign.fr) de l\'IGN.
-   Le modèle numérique de terrain détendancé permet également de visualiser d\'anciennes annexes fluviales ou d\'anciens tracés.
-   La détermination des styles fluviaux actuels définis dans le guide EBF de l\'Agence de l\'Eau (2016) peut s\'appuyer notamment sur la pente du talweg, l\'indice de sinuosité et la visualisation des images aériennes ou satellitaires. Ils sont à mettre en parallèle avec les aménagements (endiguement, barrage, rectification...) disponibles en partie avec les données du référentiel des obstacles à l\'écoulement (ROE), les ouvrages de protections contre les inondations et plus généralement avec l\'occupation du sol dans les fonds de vallée, avec une attention particulière aux infrastructures de transport.

